/**
 * TRUST — document shell: head, sticky header with navigation, the cover metadata block,
 * and the footer. Sections are composed into the middle by index.mjs.
 */

import { esc } from "./html.mjs";
import { STYLE, SUN_SVG, PRINT_SVG } from "./theme.mjs";
import { REPORT_SCRIPT } from "./client.mjs";
import { TOOL } from "../report.mjs";

export function renderHead(model) {
  const { assessmentName, target, environment, dateStr, totalRequests, profileBadges } = model;
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(assessmentName)}</title>
<link rel="icon" href="data:,"/>
${STYLE}
</head>
<body>

<header>
  <div class="header-inner">
    <div>
      <div class="report-title"><span class="brand">${esc(TOOL.name)}</span></div>
      <div class="report-sub">${esc(assessmentName)} · ${esc(target)} · ${esc(dateStr)}</div>
    </div>
    <div class="header-controls">
      <button class="control-btn" onclick="toggleTheme()" title="Toggle light/dark mode">${SUN_SVG}</button>
      <button class="control-btn" onclick="window.print()" title="Print / Save as PDF">${PRINT_SVG}</button>
    </div>
  </div>
  <nav class="report-nav">
    <a class="nav-pill active" href="#section-summary" onclick="navTo(this)">Posture</a>
    <a class="nav-pill" href="#section-scope" onclick="navTo(this)">Scope</a>
    <a class="nav-pill" href="#section-findings" onclick="navTo(this)">Findings</a>
    <a class="nav-pill" href="#section-profiles" onclick="navTo(this)">Profiles</a>
    <a class="nav-pill" href="#section-remediation" onclick="navTo(this)">Remediation</a>
    <a class="nav-pill" href="#section-retest" onclick="navTo(this)">Retest</a>
    <a class="nav-pill" href="#section-inventory" onclick="navTo(this)">Inventory</a>
    <a class="nav-pill" href="#section-trends" onclick="navTo(this)">Trends</a>
    <a class="nav-pill" href="#section-definitions" onclick="navTo(this)">Definitions</a>
  </nav>
</header>

<main>

<div class="cover">
  <table class="cover-meta">
    <tr><td>Target</td><td>${esc(target)}</td></tr>
    <tr><td>Environment</td><td><span class="env-badge">${esc(environment)}</span></td></tr>
    <tr><td>Assessment Date</td><td>${esc(dateStr)}</td></tr>
    <tr><td>Classification</td><td>Internal — Security Sensitive</td></tr>
    <tr><td>Assessment Type</td><td>Authorised, non-destructive security verification</td></tr>
    <tr><td>Profiles Executed</td><td>${profileBadges}</td></tr>
    <tr><td>Total HTTP Requests</td><td>${totalRequests}</td></tr>
    <tr><td>Harness</td><td>${esc(TOOL.name)} ${esc(TOOL.version)} — ${esc(TOOL.tagline)}</td></tr>
  </table>
</div>

<div class="callout">This report contains no access tokens, passwords, session secrets or PII. Sensitive evidence is redacted at generation time by the finding factory.</div>`;
}

export function renderFoot() {
  return `<div class="footer">
  <p>Generated by ${esc(TOOL.name)} ${esc(TOOL.version)} · Classification: Internal — Security Sensitive · Distribute only to authorised personnel</p>
</div>

</main>

${REPORT_SCRIPT}
</body>
</html>`;
}
